image: bigdft/sdk:ubuntu18.04_cuda10.0_ompi4.0.0

stages:
  - build
  - check
  - deploy

build:
  stage: build
  script:
    - ./Installer.py -y autogen
    - mkdir tmp
    - cd tmp/
    - ../Installer.py -y -f ../rcfiles/jhbuildrc build
    - ../jhbuild.py -f ../rcfiles/jhbuildrc dist --dist-only bigdft-suite
  artifacts:
    expire_in: 2 hour
    paths:
      - tmp/bigdft-suite*
      - tmp/install
      - futile
      - tmp/futile
      - atlab
      - tmp/atlab
      - psolver
      - tmp/psolver
      - bigdft
      - tmp/bigdft

futile:
  stage: check
  script:
    - cd tmp/futile
    - OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=2 run_parallel="mpirun -np 3 --allow-run-as-root --oversubscribe" PYTHONPATH=$PYTHONPATH:${CI_PROJECT_DIR}/tmp/install/lib/python2.7/site-packages/ make check

atlab:
  stage: check
  script:
    - cd tmp/atlab
    - OMP_NUM_THREADS=2 make check

psolver:
  stage: check
  script:
    - cd tmp/psolver
    - OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=2 run_parallel="mpirun -np 3 --allow-run-as-root --oversubscribe" make check

bigdft-cubic:
  stage: check
  script:
    - cd tmp/bigdft/tests/DFT/cubic
# LD_LIBRARY_PATH is for libbabel.so
    - OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=2 run_parallel="mpirun -np 3 --allow-run-as-root --oversubscribe" LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CI_PROJECT_DIR}/tmp/install/lib CHECK_MODE=short make check

bigdft-linear:
  stage: check
  allow_failure: true
  script:
    - cd tmp/bigdft/tests/DFT/linear
# LD_LIBRARY_PATH is for libbabel.so
    - OMPI_MCA_btl_vader_single_copy_mechanism=none OMP_NUM_THREADS=2 run_parallel="mpirun -np 3 --allow-run-as-root --oversubscribe" LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CI_PROJECT_DIR}/tmp/install/lib CHECK_MODE=short make check

#sphinx:
#  stage: build
#  before_script:
#    - apt update && apt -y install python-sphinx python-sphinx-bootstrap-theme
#  script:
#    - make -f Makefile-sphinx html
#  artifacts:
#    paths:
#      - "build/html"

#pages:
#  stage: deploy
#  script:
#    - mv tmp/doc/Doxygen/html ${CI_PROJECT_DIR}/public/
#    - mv tmp/psolver*.tar.bz2 ${CI_PROJECT_DIR}/public/
#    - mv libpsolver*.deb ${CI_PROJECT_DIR}/public/
#  artifacts:
#    paths:
#      - public
