image: luigigenovese/v_sim-dev

stages:
  - build
  - package
  - deploy

default:
  stage: build
  before_script:
    - apt update && apt -y install libopenmpi-dev openmpi-bin libopenmpi1.10
  script:
    - ./Installer.py -y autogen
    - mkdir tmp
    - cd tmp/
    - ../Installer.py -y -f ../rcfiles/jhbuildrc build
    - ../jhbuild.py -f ../rcfiles/jhbuildrc dist --dist-only bigdft-suite
    - cd bigdft/tests/DFT/cubic
    - OMP_NUM_THREADS=2 run_parallel="mpirun -np 3 --allow-run-as-root" CHECK_MODE=short LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CI_PROJECT_DIR}/tmp/install/lib make check
  artifacts:
    paths:
      - tmp/bigdft-suite*

#sphinx:
#  stage: build
#  before_script:
#    - apt update && apt -y install python-sphinx python-sphinx-bootstrap-theme
#  script:
#    - make -f Makefile-sphinx html
#  artifacts:
#    paths:
#      - "build/html"

#pages:
#  stage: deploy
#  script:
#    - mv tmp/doc/Doxygen/html ${CI_PROJECT_DIR}/public/
#    - mv tmp/psolver*.tar.bz2 ${CI_PROJECT_DIR}/public/
#    - mv libpsolver*.deb ${CI_PROJECT_DIR}/public/
#  artifacts:
#    paths:
#      - public
