image: ubuntu:latest

before_script:
  - apt update && apt -y install wget autoconf make pkg-config gfortran libblas3 liblapack3 libopenmpi2 libpython2.7 libyaml-0-2 python-numpy python-numpy-abi9 python-yaml
  - wget l_sim.gitlab.io/futile/libfutile_1.8-1_amd64.deb
  - dpkg -i libfutile_1.8-1_amd64.deb

stages:
  - build
  - package
  - deploy

serial:
  stage: build
  script: 
    - autoreconf -fi
    - mkdir tmp
    - cd tmp/
    - ../configure FCFLAGS="-g -O2 -fbounds-check -fopenmp -I/usr/include"
    - make -j$(nproc)
    - make dist-bzip2
    - OMP_NUM_THREADS=2 make check
  artifacts:
    when: always
    paths:
      - "tmp/atlab*.tar.bz2"

#sphinx:
#  stage: build
#  before_script:
#    - apt update && apt -y install python-sphinx python-sphinx-bootstrap-theme
#  script:
#    - make -f Makefile-sphinx html
#  artifacts:
#    paths:
#      - "build/html"

debian:
  stage: package
  script:
    - tar -xf tmp/atlab-*.tar.bz2
    - cp tmp/atlab-*.tar.bz2 $(echo $(ls tmp/atlab-*.tar.bz2) | sed "s;tmp/atlab-\(.*\).tar.bz2;atlab_\1.orig.tar.bz2;")
    - cp -rp debian/ atlab-*
    - cd atlab-*
    - apt update && apt -y install debhelper fakeroot
    - dpkg-buildpackage -rfakeroot
  artifacts:
    paths:
      - "libatlab*.deb"

pages:
  stage: deploy
  script:
#    - mv build/html/ ${CI_PROJECT_DIR}/public/
    - mkdir ${CI_PROJECT_DIR}/public
    - mv tmp/atlab*.tar.bz2 ${CI_PROJECT_DIR}/public/
    - mv libatlab*.deb ${CI_PROJECT_DIR}/public/
  artifacts:
    paths:
      - public
